### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by oagna** [waleed87w/odd_even_number_java#1]
It somehow doesn't work

**Comment by a1sewaa** [comment]
Hello Sir. Sorry for that, I did not upload file for that project and what you saw in the folder was merely a description in the file called README.md. However I have uploaded the java file for the project and it will work fine. The code inside the main class is the one that should be you are looking for. Thank you

**Comment by oagna** [comment]
Thank you I will use it as a dependency for my project!
